keys:
  - UserId
#  - client_id

hash_columns:
  - UserName
  - Gender
  - BirthYear
  - BirthMonth
  - CurrentAge
  - RetirementAge
  - UserAddress1
  - UserAddress2
  - UserAddress3
  - PerCapitaIncome
  - UserIncome
  - UserDebt
  - CreditScore
  - TotalCreditLimit
  - NumOfCards
  - BatchId
  # - current_age
  # - retirement_age
  # - birth_year
  # - birth_month
  # - gender
  # - address
  # - latitude
  # - longitude
  # - per_capita_income
  # - yearly_income
  # - total_debt
  # - credit_score
  # - num_credit_cards

audit_columns:
  CreateUser: CreateUser
  CreateDate: CreateDate
  CreateProcess: CreateProcess
  UpdateUser: UpdateUser
  UpdateDate: UpdateDate
  UpdateProcess: UpdateProcess
  StartDate: StartDate
  EndDate: EndDate
  ActiveStatus: ActiveStatus

audit_values:
  CreateUser: cpprod
  UpdateUser: cpprod
  ActiveStatus_active: A
  ActiveStatus_inactive: D

options:
  soft_delete: false   # enable or disable soft delete
